version: '2'
services:
    php:
        image: marekhanzal/php:7.3
        container_name: edde
        hostname: edde
        restart: always
        ports:
            - "4088:80"
            - "4022:22"
        volumes:
            - source:/var/www
        networks:
            - edde

    mysql:
        image: mysql:5.7
        container_name: edde-mysql
        hostname: edde-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        networks:
            - edde
        ports:
            - "4306:3306"

volumes:
    source:

networks:
    edde:
